### PR TITLE
Simplify percentile data init

### PR DESCRIPTION
**Pull request by MoseleyS**
For #1402.
Replaces single-use function with the result of that function.

Testing:
 - [x] Ran tests and they passed OK

### CODE REVIEW

**Comment by cgsandford** [comment]
Fair enough - but doesn't this break all the tests where `gen_percentile_data` is called?  If so I can just make this change in my PR if you want.

**Comment by MoseleyS** [comment]
I didn't think gen_percentile_data was called anywhere else. I can't find any calls in my working copy and I don't remember seeing any in your PR.

**Comment by MoseleyS** [comment]
PS. All the tests have passed in this PR!

**Review by cgsandford — APPROVED** [review]
Oh yes.  That'll teach me not to read the whole PR...  I'll merge this into mine now.

**Pull request merged**
